# Generated by Django 5.0.7 on 2024-07-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='criteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField()),
                ('points', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Rewarding Criteria',
                'verbose_name_plural': 'Rewarding Criterias',
            },
        ),
    ]
