# Generated by Django 5.0.7 on 2024-07-14 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0003_publication_url_alter_publication_identification'),
        ('controller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='central.publication')),
            ],
            options={
                'verbose_name': 'Pending Proposal',
                'verbose_name_plural': 'Pending Proposals',
            },
        ),
    ]
