# Generated by Django 5.0.7 on 2024-07-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0002_pending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pending',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
