# Generated by Django 5.0.7 on 2024-07-15 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0003_alter_pending_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pending',
            name='Controller',
            field=models.BooleanField(default=False, null=True, verbose_name='Controller Approval Status'),
        ),
        migrations.AddField(
            model_name='pending',
            name='hodapproval',
            field=models.BooleanField(default=False, null=True, verbose_name='HoD Approval Status'),
        ),
    ]
