# Generated by Django 5.0.7 on 2024-07-20 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0004_pending_controller_pending_hodapproval'),
    ]

    operations = [
        migrations.CreateModel(
            name='rewardcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('criterias', models.ManyToManyField(to='controller.criteria')),
            ],
            options={
                'verbose_name': 'Reward Category',
                'verbose_name_plural': 'Reward Categories',
            },
        ),
    ]
