# Generated by Django 5.0.7 on 2024-07-20 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0005_rewardcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='achievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievementid', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='controller.rewardcategory')),
            ],
            options={
                'verbose_name': 'All Achievement',
                'verbose_name_plural': 'All Acheivements',
            },
        ),
        migrations.DeleteModel(
            name='pending',
        ),
    ]
