# Generated by Django 5.0.7 on 2024-07-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0006_achievements_delete_pending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievements',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
