# Generated by Django 5.0.7 on 2024-07-20 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0008_alter_achievements_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievements',
            options={'verbose_name': 'Achievement', 'verbose_name_plural': 'All Acheivements'},
        ),
    ]
