# Generated by Django 5.0.7 on 2024-07-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0009_alter_achievements_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievements',
            name='approvalstatus',
            field=models.BooleanField(default=False),
        ),
    ]
