# Generated by Django 5.0.7 on 2024-07-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0010_achievements_approvalstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievements',
            name='approvalstatus',
            field=models.CharField(choices=[('Not Approved', 'Not Approved'), ('HoD Approved', 'HoD Approved'), ('Controller Approved', 'Controller Approved')], default='Not Approved', max_length=50),
        ),
    ]
