# Generated by Django 5.0.7 on 2024-07-24 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0013_achievements_department_remove_achievements_staff_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='rewardpoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField()),
                ('achid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='controller.achievements', verbose_name='Achievement ID')),
                ('rc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='controller.rewardcategory', verbose_name='Reward Category')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reward Point',
                'verbose_name_plural': 'Reward Points',
            },
        ),
    ]
