# Generated by Django 5.0.7 on 2024-07-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0014_rewardpoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardpoints',
            name='rctr',
            field=models.ManyToManyField(to='controller.criteria'),
        ),
    ]
