# Generated by Django 5.0.7 on 2024-07-26 06:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0016_alter_rewardpoints_points_alter_rewardpoints_rctr'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardpoints',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
