# Generated by Django 5.0.7 on 2024-07-14 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='dept',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='authentication.department'),
            preserve_default=False,
        ),
    ]
