# Generated by Django 5.0.7 on 2024-07-14 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_staff_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.department'),
        ),
    ]
