# Generated by Django 5.0.7 on 2024-07-14 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_staff_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='hod',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hod', to=settings.AUTH_USER_MODEL),
        ),
    ]
