# Generated by Django 5.0.7 on 2024-07-21 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_department_hod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.department'),
        ),
    ]
