# Generated by Django 5.0.7 on 2024-07-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='Controller',
            field=models.BooleanField(default=False, null=True, verbose_name='Controller Approval Status'),
        ),
        migrations.AddField(
            model_name='publication',
            name='hodapproval',
            field=models.BooleanField(default=False, null=True, verbose_name='HoD Approval Status'),
        ),
    ]
