# Generated by Django 5.0.7 on 2024-07-15 14:01

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_department_hod'),
        ('central', '0003_publication_url_alter_publication_identification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 7, 15, 14, 1, 27, 313296, tzinfo=datetime.timezone.utc), verbose_name='Date of publication'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='department',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.department'),
        ),
        migrations.CreateModel(
            name='consultancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('agency', models.CharField(max_length=50)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('amount', models.PositiveIntegerField()),
                ('department', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.department')),
                ('staffs', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
