# Generated by Django 5.0.7 on 2024-07-15 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_department_hod'),
        ('central', '0004_publication_date_publication_department_consultancy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultancy',
            options={'verbose_name_plural': 'Consultancies'},
        ),
        migrations.AlterField(
            model_name='consultancy',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.department'),
        ),
    ]
