# Generated by Django 5.0.7 on 2024-07-15 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_department_hod'),
        ('central', '0005_alter_consultancy_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.department'),
        ),
    ]
