# Generated by Django 5.0.7 on 2024-07-16 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0006_alter_publication_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultancy',
            name='category',
            field=models.CharField(choices=[('consultancy', 'consultancy'), ('funding', 'funding')], default='consultancy', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultancy',
            name='receivedamount',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultancy',
            name='sanctionedamount',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultancy',
            name='uc',
            field=models.BooleanField(default=False),
        ),
    ]
