# Generated by Django 5.0.7 on 2024-07-16 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0008_alter_consultancy_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultancy',
            name='receivedamount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultancy',
            name='sanctionedamount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
