# Generated by Django 5.0.7 on 2024-07-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0009_alter_consultancy_receivedamount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultancy',
            name='status',
            field=models.CharField(choices=[('sanctioned', 'sanctioned'), ('sranted', 'sranted')], default='sanctioned', max_length=10),
            preserve_default=False,
        ),
    ]
