# Generated by Django 5.0.7 on 2024-07-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0010_consultancy_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultancy',
            name='status',
            field=models.CharField(blank=True, choices=[('sanctioned', 'sanctioned'), ('sranted', 'sranted')], max_length=10, null=True),
        ),
    ]
