# Generated by Django 5.0.7 on 2024-07-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0011_alter_consultancy_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultancy',
            name='sanctionedamount',
        ),
        migrations.AlterField(
            model_name='consultancy',
            name='status',
            field=models.CharField(blank=True, choices=[('sanctioned', 'sanctioned'), ('sranted', 'granted')], max_length=10, null=True),
        ),
    ]
