# Generated by Django 5.0.7 on 2024-07-17 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0012_remove_consultancy_sanctionedamount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultancy',
            name='status',
            field=models.CharField(blank=True, choices=[('sanctioned', 'sanctioned'), ('granted', 'granted')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='identification',
            field=models.CharField(max_length=25, unique=True, verbose_name='ISSN/DOI No'),
        ),
    ]
