# Generated by Django 5.0.7 on 2024-07-17 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0013_alter_consultancy_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultancy',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
