# Generated by Django 5.0.7 on 2024-07-17 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_department_hod'),
        ('central', '0014_alter_consultancy_name_alter_publication_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ipr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('copyright', 'copyright'), ('trademark', 'trademark'), ('patent', 'patent')], max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('uniqueno', models.CharField(max_length=50)),
                ('patentoffice', models.CharField(max_length=50)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.department')),
            ],
        ),
    ]
