# Generated by Django 5.0.7 on 2024-07-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0015_ipr'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ipr',
            options={'verbose_name': 'IPR', 'verbose_name_plural': 'IPR'},
        ),
        migrations.AddField(
            model_name='ipr',
            name='status',
            field=models.CharField(choices=[('filing', 'filing'), ('granted', 'granted')], default='filing', max_length=50),
            preserve_default=False,
        ),
    ]
