# Generated by Django 5.0.7 on 2024-07-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0017_alter_ipr_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultancy',
            name='Controller',
            field=models.BooleanField(default=False, null=True, verbose_name='Controller Approval Status'),
        ),
        migrations.AddField(
            model_name='consultancy',
            name='hodapproval',
            field=models.BooleanField(default=False, null=True, verbose_name='HoD Approval Status'),
        ),
        migrations.AddField(
            model_name='ipr',
            name='Controller',
            field=models.BooleanField(default=False, null=True, verbose_name='Controller Approval Status'),
        ),
        migrations.AddField(
            model_name='ipr',
            name='hodapproval',
            field=models.BooleanField(default=False, null=True, verbose_name='HoD Approval Status'),
        ),
        migrations.AlterField(
            model_name='ipr',
            name='status',
            field=models.CharField(blank=True, choices=[('filing', 'filing'), ('granted', 'granted')], max_length=50, null=True),
        ),
    ]
