# Generated by Django 5.0.7 on 2024-07-17 12:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0018_consultancy_controller_consultancy_hodapproval_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ipr',
            name='staffs',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
