# Generated by Django 5.0.7 on 2024-07-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0019_ipr_staffs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipr',
            name='uniqueno',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
