# Generated by Django 5.0.7 on 2024-07-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0020_alter_ipr_uniqueno'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipr',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
