# Generated by Django 5.0.7 on 2024-07-17 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0022_phd'),
    ]

    operations = [
        migrations.AddField(
            model_name='phd',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 7, 17, 15, 13, 26, 111870, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='phd',
            name='type',
            field=models.CharField(choices=[('Guideship', 'Guideship'), ('Ongoing Scholar', 'Ongoing Scholar'), ('Completed Scholar', 'Completed Scholar')], max_length=50),
        ),
    ]
