# Generated by Django 5.0.7 on 2024-07-17 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_department_hod'),
        ('central', '0023_phd_date_alter_phd_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='phd',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.department'),
        ),
        migrations.AlterField(
            model_name='ipr',
            name='category',
            field=models.CharField(choices=[('Patent Filing', 'Patent Filing'), ('Patent Grant', 'Patent Grant'), ('Design Filing', 'Design Filing'), ('Design Grant', 'Design Grant'), ('Copyright Filing', 'Copyright Filing'), ('Copyright Registered', 'Copyright Registered'), ('copyright', 'copyright'), ('trademark', 'trademark'), ('patent', 'patent')], max_length=50),
        ),
    ]
