# Generated by Django 5.0.7 on 2024-07-17 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_department_hod'),
        ('central', '0025_alter_phd_registerno_alter_phd_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='r1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('STTP', 'STTP'), ('FDP', 'FDP')], max_length=25)),
                ('timeperiods', models.CharField(choices=[('Upto 2 days', 'Upto 2 days'), ('Upto 1 week', 'Upto 1 week'), ('2 weeks and above', '2 weeks and above')], max_length=50)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.department')),
                ('staffs', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
