# Generated by Django 5.0.7 on 2024-07-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0027_alter_r1_options_alter_r1_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='r1',
            options={'verbose_name': 'Research Related Attending & Awards', 'verbose_name_plural': 'Research Related Attendings & Awards'},
        ),
        migrations.AddField(
            model_name='r1',
            name='modeltype',
            field=models.CharField(choices=[('Attending', 'Attending'), ('Award', 'Award')], default='Attending', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='r1',
            name='type',
            field=models.CharField(choices=[('STTP', 'STTP'), ('FDP', 'FDP  (NPTEL excluded)'), ('Seminar', 'Seminar'), ('Workshop', 'Workshop')], max_length=25),
        ),
    ]
