# Generated by Django 5.0.7 on 2024-07-19 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_department_hod'),
        ('central', '0029_remove_r1_modeltype_awards'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='awards',
            options={'verbose_name': 'Award', 'verbose_name_plural': 'Awards'},
        ),
        migrations.CreateModel(
            name='r2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.CharField(max_length=50)),
                ('duration', models.CharField(choices=[('Succesfully completed 4 weeks', 'Succesfully completed 4 weeks'), ('Succesfully completed 8 weeks', 'Succesfully completed 8 weeks'), ('Succesfully completed 12 weeks', 'Succesfully completed 12 weeks')], max_length=50)),
                ('mark', models.PositiveIntegerField()),
                ('institution', models.CharField(max_length=75)),
                ('certificateno', models.CharField(max_length=35)),
                ('date', models.DateField()),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.department')),
                ('staffs', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Research Related Course',
                'verbose_name_plural': 'Research Related Courses',
            },
        ),
    ]
