# Generated by Django 5.0.7 on 2024-07-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0031_remove_r2_staffs_r2_staffs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='r2',
            name='certificateno',
            field=models.CharField(max_length=35, unique=True),
        ),
    ]
