# Generated by Django 5.0.7 on 2024-07-19 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_department_hod'),
        ('central', '0033_alter_r2_staffs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='r3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], max_length=50)),
                ('category', models.CharField(choices=[('Reputed academics institutions abroad top NIRF', 'Reputed academics institutions abroad top NIRF etc'), ('Industries', 'Industries')], max_length=50)),
                ('mark', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.department')),
                ('staffs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acted as a Resource person',
                'verbose_name_plural': 'Acted as a Resource person',
            },
        ),
    ]
