# Generated by Django 5.0.7 on 2024-07-19 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0034_r3'),
    ]

    operations = [
        migrations.AddField(
            model_name='r3',
            name='location',
            field=models.CharField(default='Earth', max_length=75),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='r3',
            name='category',
            field=models.CharField(choices=[('Reputed academics institutions abroad top NIRF', 'Reputed academics institutions abroad top NIRF etc'), ('Industries', 'Industries'), ('Developed Course modules on Swayam-NPTEL or Coursera (minimum: 1hr)', 'Developed Course modules Swayam-NPTEL or Coursera (minimum: 1hr)')], max_length=100),
        ),
    ]
