# Generated by Django 5.0.7 on 2024-07-19 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0035_r3_location_alter_r3_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='r3',
            name='mark',
        ),
    ]
