# Generated by Django 5.0.7 on 2024-07-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0036_remove_r3_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='r3',
            name='purpose',
            field=models.TextField(default='Example'),
            preserve_default=False,
        ),
    ]
