# Generated by Django 5.0.7 on 2024-07-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0041_rename_controller_ipr_controller'),
    ]

    operations = [
        migrations.AddField(
            model_name='r1',
            name='controller',
            field=models.BooleanField(default=False, null=True, verbose_name='Controller Approval Status'),
        ),
        migrations.AddField(
            model_name='r1',
            name='hodapproval',
            field=models.BooleanField(default=False, null=True, verbose_name='HoD Approval Status'),
        ),
    ]
