# Generated by Django 5.0.7 on 2024-07-22 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0042_r1_controller_r1_hodapproval'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultancy',
            old_name='Controller',
            new_name='controller',
        ),
    ]
