# Generated by Django 5.0.7 on 2024-07-23 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_staff_dept'),
        ('central', '0043_rename_controller_consultancy_controller'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultancy',
            options={'verbose_name': 'Consultancy', 'verbose_name_plural': 'Consultancies'},
        ),
        migrations.AlterModelOptions(
            name='r1',
            options={'verbose_name': 'Research Related Attending (STTP/FDP)', 'verbose_name_plural': 'Research Related Attendings (STTP/FDP)'},
        ),
        migrations.CreateModel(
            name='funding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('agency', models.CharField(max_length=50)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('amount', models.PositiveIntegerField()),
                ('status', models.CharField(blank=True, choices=[('sanctioned', 'sanctioned'), ('granted', 'granted')], max_length=10, null=True)),
                ('receivedamount', models.PositiveIntegerField(blank=True, null=True)),
                ('uc', models.BooleanField(blank=True, default=False)),
                ('hodapproval', models.BooleanField(default=False, null=True, verbose_name='HoD Approval Status')),
                ('controller', models.BooleanField(default=False, null=True, verbose_name='Controller Approval Status')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.department')),
                ('staffs', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Funding',
                'verbose_name_plural': 'Fundings',
            },
        ),
    ]
