# Generated by Django 5.0.7 on 2024-07-23 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0044_alter_consultancy_options_alter_r1_options_funding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultancy',
            name='category',
        ),
        migrations.RemoveField(
            model_name='consultancy',
            name='receivedamount',
        ),
        migrations.RemoveField(
            model_name='consultancy',
            name='status',
        ),
        migrations.RemoveField(
            model_name='consultancy',
            name='uc',
        ),
    ]
