# Generated by Django 5.0.7 on 2024-07-23 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_staff_dept'),
        ('central', '0045_remove_consultancy_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='d1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=50)),
                ('noc', models.PositiveIntegerField()),
                ('mark', models.PositiveIntegerField()),
                ('certificateno', models.CharField(max_length=35, unique=True)),
                ('date', models.DateField()),
                ('hodapproval', models.BooleanField(default=False, null=True, verbose_name='HoD Approval Status')),
                ('controller', models.BooleanField(default=False, null=True, verbose_name='Controller Approval Status')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.department')),
                ('staffs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Domain Certification',
                'verbose_name_plural': 'Domain Certifications',
            },
        ),
    ]
