# Generated by Django 5.0.7 on 2024-07-23 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0046_d1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='identification',
        ),
        migrations.AddField(
            model_name='publication',
            name='ISSN',
            field=models.CharField(default=23134, max_length=25, verbose_name='ISSN/DOI No'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='doi',
            field=models.CharField(default=1231414, max_length=25, verbose_name='ISSN/DOI No'),
            preserve_default=False,
        ),
    ]
