# Generated by Django 5.0.7 on 2024-07-23 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0047_remove_publication_identification_publication_issn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='ISSN',
            field=models.CharField(max_length=25, unique=True, verbose_name='ISSN/DOI No'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='doi',
            field=models.CharField(max_length=25, unique=True, verbose_name='ISSN/DOI No'),
        ),
    ]
