# Generated by Django 5.0.7 on 2024-07-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0048_alter_publication_issn_alter_publication_doi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='ISSN',
        ),
        migrations.AlterField(
            model_name='publication',
            name='doi',
            field=models.CharField(max_length=25, unique=True, verbose_name='ISSN No'),
        ),
        migrations.AddField(
            model_name='publication',
            name='issn',
            field=models.CharField(default=765765, max_length=25, unique=True, verbose_name='DOI No'),
            preserve_default=False,
        ),
    ]
