# Generated by Django 5.0.7 on 2024-07-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0051_remove_consultancy_pi_funding_pi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funding',
            name='status',
            field=models.CharField(blank=True, choices=[('sanctioned', 'sanctioned'), ('submitted', 'submitted')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ipr',
            name='category',
            field=models.CharField(choices=[('Patent Filing', 'Patent Filing'), ('Patent Granted', 'Patent Granted'), ('Design Filing', 'Design Filing'), ('Design Granted', 'Design Granted'), ('Copyright Filing', 'Copyright Filing'), ('Copyright Registered', 'Copyright Registered')], max_length=50),
        ),
        migrations.AlterField(
            model_name='phd',
            name='type',
            field=models.CharField(choices=[('Guideship', 'Guideship'), ('Ongoing Scholar', 'Ongoing Scholar'), ('Completed Scholar', 'Completed Scholar')], max_length=50),
        ),
        migrations.AlterField(
            model_name='r3',
            name='category',
            field=models.TextField(choices=[('Reputed academic institutions from abroad, top NIRF-ranked government and government-aided institutions', 'Reputed academic institutions from abroad, top NIRF-ranked government and government-aided institutions'), ('Industries', 'Industries'), ('Course modules developed for online content in Swayam-NPTEL, Coursera (for 1 hour)', 'Course modules developed for online content in Swayam-NPTEL, Coursera (for 1 hour)')]),
        ),
    ]
