# Generated by Django 5.0.7 on 2024-07-29 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0052_alter_funding_status_alter_ipr_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='awards',
            name='institutiontype',
            field=models.CharField(choices=[('RC029', 'RC029'), ('RC030', 'RC030'), ('RC031', 'RC031'), ('RC032', 'RC032')], max_length=150),
        ),
        migrations.RemoveField(
            model_name='r1',
            name='staffs',
        ),
        migrations.AlterField(
            model_name='r3',
            name='category',
            field=models.TextField(choices=[('reputed institutions abroad', 'reputed institutions abroad'), ('industries', 'industries'), ('course modules', 'course modules')]),
        ),
        migrations.AddField(
            model_name='r1',
            name='staffs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
