# Generated by Django 5.0.7 on 2024-07-31 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0054_r2_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phd',
            name='type',
            field=models.CharField(choices=[('Ongoing', 'Ongoing'), ('Completed', 'Completed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='publication',
            name='doi',
            field=models.CharField(max_length=25, null=True, unique=True, verbose_name='ISSN No'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='issn',
            field=models.CharField(max_length=25, null=True, unique=True, verbose_name='DOI No'),
        ),
    ]
