# Generated by Django 5.0.7 on 2024-07-31 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0055_alter_phd_type_alter_publication_doi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='guide',
        ),
    ]
