# Generated by Django 5.0.7 on 2024-07-31 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0056_remove_publication_guide'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='count',
            field=models.PositiveIntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='isbn',
            field=models.CharField(max_length=25, null=True, unique=True, verbose_name='ISBN No'),
        ),
    ]
