# Generated by Django 5.0.7 on 2024-08-04 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0057_publication_count_publication_isbn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultancy',
            old_name='enddate',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='funding',
            old_name='enddate',
            new_name='date',
        ),
    ]
